### ISSUE TITLE
Detecting CrossCode Version

### ISSUE THREAD

**Issue by Vankerkom** [CCDirectLink/CCLoader#12]
As taken from the Discord chat:

It would be useful to have some functionality which allows a mod to detect which version of CrossCode is running.

> pwned by xXxScriptKiddiexXxToday at 1:28 AM
Need to have a system that verifies which version of crosscode it can be ran on.

**Comment by 2767mr** [comment]
Added version support for mods in the latest update. See https://github.com/CCDirectLink/CCLoader/wiki/Configuration-File
