### ISSUE TITLE
no such file or directory ccloader/data/assets\mods\ccloader-version-display

### ISSUE THREAD

**Issue by LoganTann** [CCDirectLink/CCLoader#38]
The game freezes when the RadicalFish logo appears for approximately 5 seconds, and display two messages : 
```
2 definitions did not match [object Object],[object Object]

Could not load definitions of mod CCLoader display version. Disabling. Error: ENOENT: no such file or directory, open 'ccloader/data/assets\mods\ccloader-version-display\b45a9940147cbb7ccd915708130221cb.table'
```
I have no ideas if it is CCloader or mods that I have installed who made this isue...
Platform : Windows 7
Cross Code version : 1.1.0
CCloader downloaded today.
Mods used : 
* discord
* french + localize-me
* slowmotion
Default mods : 
* ccloader-version-display
* openDevTools
* simplify

**Comment by 2767mr** [comment]
This issue is caused by a system that was used to support modding for CrossCode before v1.1.0. However, this issue should only appear on the first start of CCLoader. As a fix we should update ccloader-version-display to not use the legacy system and restrict it to >= 1.1.0.
Thank you for reporting!
