### ISSUE TITLE
Is there a way to temporarily disable CCloader ?

### ISSUE THREAD

**Issue by LoganTann** [CCDirectLink/CCLoader#39]
This is more a question than an issue but I would like to know if it is possible to run the game without CCloader (this is mainly for testing purpose :joy: ).
Indeed, the Readme/Wiki explains how to install but to disable ... ?

**Comment by 2767mr** [comment]
There is no automated way to do this (and there proprobably never will be).
The best way to do this is to restore the original `package.json` file. If you do that, it will not load CCLoader or any mods.
```json
{
  "name": "CrossCode",
  "version" : "1.0.0",
  "main": "assets/node-webkit.html",
  "chromium-args" : "--ignore-gpu-blacklist --disable-direct-composition --disable-background-networking --in-process-gpu --password-store=basic",
  "window" : {
	"toolbar" : false,
	"icon" : "favicon.png",
	"width" : 1136,
	"height": 640,
	"fullscreen" : false
  }
}
```
